name: deploy react app
on:
  push:
    branches:
      - master
jobs:
  job_01-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get_repository_code
        uses: actions/checkout@v3
      - name: cache_test
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}    
      - name: install_dependecies
        run: npm install
      - name: test_application
        run: npm run test
  job_02-lint:
    runs-on: ubuntu-latest
    needs: job_01-test
    steps:
      - name: get_repository_code
        uses: actions/checkout@v3
      - name: cache_test
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: install_dependecies
        run: npm install
      - name: lint appclication
        run: npm run lint
  job_03-build:
    needs: job_02-lint
    strategy:
      matrix:
        key-matrix_01-version: [14, 16]
        key-matrix_02-os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.key-matrix_02-os }}
    steps:
      - name: get_repository_code
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.key-matrix_01-version }}
      - name: cache_test
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: install_dependecies
        run: npm install
      - name: build application
        run: npm run build
      - name: deploy
        run: echo "Deploy - started..."
