name: print pull request context 
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  job_01-print:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        run: echo "${{ toJSON(github.event) }}"
