name: Test_WorkFlow
on: workflow_dispatch
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: steps_01
        run: echo "Heelo, its my first CI\CD"
      - name: steps_02
        run: echo -e "1\n2\n3\n4"
